const express=require('express');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const User=require('../models/User'); 

const router=express.Router();


// why we use async await ? because we are dealing with asynchronous operations like database queries and hashing passwords, and using async/await makes the code cleaner and easier to read compared to using callbacks or promises
// i.e it stops the executuion of the program until it gets the value from the function, once it gets the value it continues with the execution of the program, this is how it makes the code cleaner and easier to read.
router.post('/signup',async(req,res)=>{
    try{
        // the name should be same as it is written in model
        const {name,email,password}=req.body;
        const existingUser=await User.findOne({email});
        if(existingUser){
            return res.status(400).json({message:'User already exists'});
        }

        // hash pass
        // const salt=await bcrypt.genSalt(10);
        const hashedPass=await bcrypt.hash(password,10);
        // 10 layer of hashing, the higher the number the more secure but also more time consuming
        const user=new User({name,email,password:hashedPass});
        await user.save();
        res.status(201).json({message:'User created successfully'});

    }catch(err){
        console.log(err);
        console.log(req.body); 

        res.status(500).json({message:'Server error'});
    }
});

router.post('/login',async(req,res)=>{
    try{
        const {email,password}=req.body;
        const user=await User.findOne({email});
        if(!user){
            return res.status(400).json({message:'Invalid credentials'});
        }
        const isMatch=await bcrypt.compare(password,user.password);
        if(!isMatch){
            return res.status(400).json({message:'Invalid credentials'});
        }
        // tokens gen to remember the password while user is using the app?
        // jwt gen to create a token that will be sent to the client and stored in the local storage or cookies, 
        // this token will be used to authenticate the user in the future requests, so that the user doesn't have to login again and again,
        // it will also help to keep the user logged in even after closing the app, until the token expires or is deleted.
         
        
        // It is basically a secure identity card generated by backend.it is digitally signed by server secret key.
        // Creates secure token containing: user._id using secretkey
        const token=jwt.sign({id:user._id},'secretkey',{expiresIn:'7d'});
        // but the model is not having the token field, so where it will store the token ? it will not store the token in the database, it will send the token to the client 
        // and the client will store it in the local storage or cookies, and then send it back to the server in the future requests for authentication.
        res.status(200).json({token,user:{id:user._id,name:user.name,email:user.email}});

    }catch(err){
        res.status(500).json({message:'Server error'});
    }
})
module.exports=router;